moWEBApp.web/Models/ErrorViewModel.cs
namespace moWEBApp.web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

moWEBApp.web/Models/MoviesViewModel.cs
using moWEBApp.web.Entity;

namespace moWEBApp.web.Models
{
    public class MoviesViewModel
    {
        public List<Movie> Movies { get; set; }
    }
}

moWEBApp.web/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using moWEBApp.web.Data;
using moWEBApp.web.Entity;
using moWEBApp.web.Models;
using System.IO;

namespace moWEBApp.web.Controllers
{
    public class MoviesController : Controller
    {
        private readonly MovieContext _context;

        public MoviesController(MovieContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List(int? id, string q)
        {
            //var movies = _context.Movies.AsQueryable();

            var movies = _context.Movies.Include(m => m.Genre).AsQueryable();

            if (id!=null)
            {
                movies = movies.Where(m => m.GenreId==id);
            }

            if(!string.IsNullOrEmpty(q))
            {
                movies = movies.Where(i => i.Title.ToLower().Contains(q.ToLower()));
            }

            var model = new MoviesViewModel()
            {
                Movies = movies.ToList()
            };

            return View("Movies", model);
        }

        public IActionResult Details(int id)
        {
            var movie = _context.Movies.Include(m => m.Genre).FirstOrDefault(m => m.MovieId == id);
            ViewBag.GenreName = movie.Genre?.Name ?? "No Genre";

            return View(_context.Movies.Find(id));
        }

        public IActionResult Create()
        {
			ViewBag.Genres = new SelectList(_context.Genres.ToList(), "GenreId", "Name");
			return View();
        }

        [HttpPost]
		public IActionResult Create(Movie m)
		{
            _context.Movies.Add(m);
            _context.SaveChanges();

			return RedirectToAction("List");
		}

        public IActionResult Edit(int id)
        {
            ViewBag.Genres = new SelectList(_context.Genres.ToList(), "GenreId", "Name");
            return View(_context.Movies.Find(id));
        }

        [HttpPost]
		public IActionResult Edit(Movie m)
		{
            _context.Movies.Update(m);
            _context.SaveChanges();
            return RedirectToAction("Details", "Movies", new {@id = m.MovieId});
		}

		[HttpPost]
		public IActionResult Delete(int MovieId)
		{
            var entity = _context.Movies.Find(MovieId);
            _context.Movies.Remove(entity);
            _context.SaveChanges();
            return RedirectToAction("List");
		}
	}
}

moWEBApp.web/ViewComponents/GenresViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using moWEBApp.web.Data;
using moWEBApp.web.Models;

namespace moWEBApp.web.ViewComponents
{
    public class GenresViewComponent: ViewComponent
    {
		private readonly MovieContext _context;

		public GenresViewComponent(MovieContext context)
		{
			_context = context;
		}

		public IViewComponentResult Invoke()
        {
            ViewBag.SelectedGenre = RouteData.Values["id"];
            return View(_context.Genres.ToList());
        }
    }
}

moWEBApp.web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


    <div class="row">
        <div class="col-md-6">
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-12 text-center">
                        <h5 class="card-header bg-dark-blue text-white h3">Film Name</h5>
                    </div>
                </div>
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="https://s3.cloud.ngn.com.tr/kitantik/images/2020-05-05/0z8kgltk9slrxe51own.jpg"
                             class="img-fluid img-thumbnail" style="height: 100%;" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <p class="card-text">
                                This is a wider card with supporting text below as a natural lead-in to additional
                                content. This content is a little bit longer.
                            </p>
                            <p><b>Cinema: </b> Cinema 1</p>
                            <p><b>Category: </b> Drama</p>
                            <p><b>Start Date: </b> 26/12/2023</p>
                            <p><b>End Date: </b> 26/12/2023</p>
                            <button type="button" class="btn btn-outline-dark float-end mb-3">Details</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-12 text-center">
                        <h5 class="card-header bg-dark-blue text-white h3">Film Name</h5>
                    </div>
                </div>
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="https://s3.cloud.ngn.com.tr/kitantik/images/2020-05-05/0z8kgltk9slrxe51own.jpg"
                             class="img-fluid img-thumbnail" style="height: 100%;" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <p class="card-text">
                                This is a wider card with supporting text below as a natural lead-in to additional
                                content. This content is a little bit longer.
                            </p>
                            <p><b>Cinema: </b> Cinema 1</p>
                            <p><b>Category: </b> Drama</p>
                            <p><b>Start Date: </b> 26/12/2023</p>
                            <p><b>End Date: </b> 26/12/2023</p>
                            <button type="button" class="btn btn-outline-dark float-end mb-3">Details</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-12 text-center">
                        <h5 class="card-header bg-dark-blue text-white h3">Film Name</h5>
                    </div>
                </div>
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="https://s3.cloud.ngn.com.tr/kitantik/images/2020-05-05/0z8kgltk9slrxe51own.jpg"
                             class="img-fluid img-thumbnail" style="height: 100%;" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <p class="card-text">
                                This is a wider card with supporting text below as a natural lead-in to additional
                                content. This content is a little bit longer.
                            </p>
                            <p><b>Cinema: </b> Cinema 1</p>
                            <p><b>Category: </b> Drama</p>
                            <p><b>Start Date: </b> 26/12/2023</p>
                            <p><b>End Date: </b> 26/12/2023</p>
                            <button type="button" class="btn btn-outline-dark float-end mb-3">Details</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-12 text-center">
                        <h5 class="card-header bg-dark-blue text-white h3">Film Name</h5>
                    </div>
                </div>
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="https://s3.cloud.ngn.com.tr/kitantik/images/2020-05-05/0z8kgltk9slrxe51own.jpg"
                             class="img-fluid img-thumbnail" style="height: 100%;" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <p class="card-text">
                                This is a wider card with supporting text below as a natural lead-in to additional
                                content. This content is a little bit longer.
                            </p>
                            <p><b>Cinema: </b> Cinema 1</p>
                            <p><b>Category: </b> Drama</p>
                            <p><b>Start Date: </b> 26/12/2023</p>
                            <p><b>End Date: </b> 26/12/2023</p>
                            <button type="button" class="btn btn-outline-dark float-end mb-3">Details</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

moWEBApp.web/Views/Movies/Create.cshtml
@model Movie

@{
	ViewData["Title"] = "Create Movie";
}

<h1 class="text-primary-emphasis text-center">Create Movie</h1>

<form method="post" asp-controller="Movies" asp-action="Create">
	<div class="mb-3 form-group">
		<label asp-for="Title" class="form-label"></label>
		<input asp-for="Title" class="form-control" placeholder="Title">
	</div>
	<div class="mb-3 form-group">
		<label asp-for="Description" class="form-label"></label>
		<textarea class="form-control" asp-for="Description" placeholder="Description"></textarea>
	</div>
	<div class="mb-3 form-group">
		<label asp-for="Director" class="form-label"></label>
		<input asp-for="Director" class="form-control" placeholder="Director">
	</div>
	<div class="mb-3 form-group">
		<label asp-for="StartDate" class="form-label"></label>
		<input asp-for="StartDate" class="form-control" type="date" placeholder="Start date">
	</div>
	<div class="mb-3 form-group">
		<label asp-for="EndDate" class="form-label"></label>
		<input asp-for="EndDate" class="form-control" type="date" placeholder="End date">
	</div>
	<div class="mb-3 form-group">
		<label asp-for="ImageUrl" class="form-label"></label>
		<input asp-for="ImageUrl" class="form-control" placeholder="Image URL">
		<span asp-validation-for="ImageUrl" class="text-danger"></span>
	</div>
	<div class="mb-3 form-group">
		<label asp-for="GenreId" class="form-label"></label>
		<select class="form-select form-control" asp-for="GenreId" asp-items="@ViewBag.Genres" aria-label="Default select example">
			<option selected disabled>Choose a genre</option>
		</select>
	</div>
	<div class="mb-3 form-group">
		<label asp-for="TrailerLink" class="form-label"></label>
		<input asp-for="TrailerLink" class="form-control" placeholder="Trailer link">
	</div>
	<button type="submit" class="btn btn-success">Submit</button>
</form>

moWEBApp.web/Views/Movies/Details.cshtml
@using System.Globalization
@using System.Text.RegularExpressions;

@model Movie

@{
    ViewData["Title"] = "Movie Detail";
}

<div class="card mb-3">
    <div class="row g-0">
        <div class="col-md-12 text-center">
            <h1 class="card-header bg-dark-blue text-white" style="font-size: 2em; font-weight:400; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.8);">@Model.Title</h1>
        </div>
    </div>
    <div class="row g-0">
        <div class="col-md-4">
            <img src="~/img/@Model.ImageUrl"
                 class="img-fluid img-thumbnail" style="height: 100%;" alt="@Model.Title">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <p class="card-text lead">
                    @Model.Description
                </p>
                <p><b>Director: </b> @Model.Director</p>
                <p><b>Category: </b>@ViewBag.GenreName</p>
                <p><b>Start Date: </b> @Model.StartDate.ToString("dd MMM yyyy", new CultureInfo("en-US"))</p>
                <p><b>End Date: </b> @Model.EndDate.ToString("dd MMM yyyy", new CultureInfo("en-US"))</p>
                <p>
                    <b>Status: </b>
                    @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                    {
                        <span class="badge bg-success text-white">AVAILABLE</span>
                    }
                    else if (DateTime.Now > Model.EndDate)
                    {
                        <span class="badge bg-danger text-white">EXPIRED</span>
                    }
                    else
                    {
                        <span class="badge bg-primary text-white">UPCOMING</span>
                    }
                </p>
                <div class="embed-responsive embed-responsive-16by9 h-100">
                    <iframe class="embed-responsive-item w-100" style="height:400px" src="https://www.youtube.com/embed/@Regex.Match(Model.TrailerLink, @"watch\?v=(.*)").Groups[1].Value" frameborder="0" allowfullscreen></iframe>
                </div>
                @* @if(Model.Players != null)
                {
                    <p>
                        <ul>
                            @foreach (var item in Model.Players)
                            {
                                <li>@item</li>
                            }
                        </ul>
                    </p>
                } *@
            </div>
        </div>
    </div>
</div>

moWEBApp.web/Views/Movies/Edit.cshtml
@model Movie

@{
	ViewData["Title"] = "Edit Movie";
}

<h1 class="text-primary-emphasis text-center">Edit Movie</h1>

<form method="post" asp-controller="Movies" asp-action="Edit">
	<input type="hidden" name="MovieId" value="@Model.MovieId">
	<div class="mb-3 form-group">
		<label asp-for="Title" class="form-label"></label>
		<input asp-for="Title" class="form-control" placeholder="Title" value="@Model.Title">
	</div>
	<div class="mb-3 form-group">
		<label asp-for="Description" class="form-label"></label>
		<textarea class="form-control" asp-for="Description" placeholder="Description">@Model.Description</textarea>
	</div>
	<div class="mb-3 form-group">
		<label asp-for="Director" class="form-label"></label>
		<input asp-for="Director" class="form-control" placeholder="Director" value="@Model.Director">
	</div>
	<div class="mb-3 form-group">
		<label asp-for="StartDate" class="form-label"></label>
		<input asp-for="StartDate" class="form-control" placeholder="Start date" type="date" value="@Model.StartDate.ToString("dd MMM yyyy")">
	</div>
	<div class="mb-3 form-group">
		<label asp-for="EndDate" class="form-label"></label>
		<input asp-for="EndDate" class="form-control" placeholder="End date" type="date" value="@Model.EndDate.ToString("dd MMM yyyy")">
	</div>
	<div class="mb-3 form-group">
		<label asp-for="ImageUrl" class="form-label"></label>
		<input asp-for="ImageUrl" class="form-control" placeholder="Image URL" value="@Model.ImageUrl">
	</div>
	<div class="mb-3 form-group">
		<label asp-for="GenreId" class="form-label"></label>
		<select class="form-select form-control" asp-for="GenreId" asp-items="@ViewBag.Genres" aria-label="Default select example">
			<option selected disabled>Choose a genre</option>
		</select>
	</div>
	<div class="mb-3 form-group">
		<label asp-for="TrailerLink" class="form-label"></label>
		<input asp-for="TrailerLink" class="form-control" placeholder="Trailer link" value="@Model.TrailerLink">
	</div>
	<button type="submit" class="btn btn-success">Submit</button>
</form>

moWEBApp.web/Views/Movies/Index.cshtml
@model Movie

@{
    ViewData["Title"] = "Movies";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="col-md-6">
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-12 text-center">
                    <h5 class="card-header bg-dark-blue text-white h3">@Model.Title</h5>
                </div>
            </div>
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="https://s3.cloud.ngn.com.tr/kitantik/images/2020-05-05/0z8kgltk9slrxe51own.jpg"
                         class="img-fluid img-thumbnail" style="height: 100%;" alt="...">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text lead">
                            @Model.Description
                        </p>
                        <p><b>Director: </b> @Model.Director</p>
                        <p><b>Category: </b> Drama</p>
                        <p><b>Start Date: </b> @Model.StartDate</p>
                        <p><b>End Date: </b> @Model.EndDate</p>
                        <button type="button" class="btn btn-outline-dark float-end mb-3">Details</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

moWEBApp.web/Views/Movies/Movies.cshtml
@using System.Globalization
@model MoviesViewModel
@{
    ViewData["Title"] = "Movies";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    @if(Model.Movies.Count() > 0)
    {
        @foreach (var movie in Model.Movies)
        {
            <div class="col-md-6">
                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="col-md-12 text-center">
                            <h1 class="card-header bg-dark-blue text-white" style="font-size: 1.6em; font-weight:400; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.8);">@movie.Title</h1>
                        </div>
                    </div>
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="~/img/@movie.ImageUrl"
                                 class="img-fluid img-thumbnail" style="height: 100%;" alt="@movie.Title">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body mb-1">
                                <p class="card-text lead">
                                    @{
                                        if (movie.Description.Length > 40)
                                        {
                                            <span>@movie.Description.Substring(0, 40) ...</span>
                                        }
                                        else
                                        {
                                            <span>@movie.Description</span>
                                        }
                                    }
                                </p>
                                <p><b>Director: </b> @movie.Director</p>
                                <p><b>Category: </b>@movie.Genre.Name</p>
                                <p><b>Start Date: </b> @movie.StartDate.ToString("dd MMM yyyy", new CultureInfo("en-US"))</p>
                                <p><b>End Date: </b> @movie.EndDate.ToString("dd MMM yyyy", new CultureInfo("en-US"))</p>
                                <p><b>Status: </b> 
                                    @if(DateTime.Now >= movie.StartDate && DateTime.Now <= movie.EndDate)
                                    {
                                        <span class="badge bg-success text-white">AVAILABLE</span>
                                    }
                                    else if(DateTime.Now > movie.EndDate)
                                    {
                                        <span class="badge bg-danger text-white">EXPIRED</span>
                                    }
                                    else
                                    {
                                        <span class="badge bg-primary text-white">UPCOMING</span>
                                    }
                                </p>
                                <div class="d-flex justify-content-end">
                                    <a class="btn btn-outline-dark me-2" asp-controller="Movies" asp-action="Details" asp-route-id="@movie.MovieId" role="button">Details</a>
                                    <a class="btn btn-outline-success me-2" asp-controller="Movies" asp-action="Edit" asp-route-id="@movie.MovieId" role="button">Edit</a>
                                    <form asp-controller="Movies" asp-action="Delete" method="post">
                                        <input type="hidden" name="MovieId" value="@movie.MovieId" />
                                        <button type="submit" class="btn btn-outline-danger">Delete</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
    else
    {
        <div class="alert alert-danger" role="alert">
            Movie Not Found!
        </div>
    }
</div>

moWEBApp.web/Views/Shared/Components/Genres/Default.cshtml
@model List<Genre>

<div class="dropdown me-2">
    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Categories
    </button>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="/Movies/List">All</a></li>
        @foreach (var genre in Model)
        {
            <li><a class="dropdown-item @(ViewBag.SelectedGenre==genre.GenreId.ToString()?"active":"")" href="/Movies/List/@genre.GenreId">@genre.Name</a></li>
        }
    </ul>
</div>

moWEBApp.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MoWEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/moWEBApp.web.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/style.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary bg-info-subtle shadow-sm fixed-top">
        <div class="container py-2 px-4">
            <a class="navbar-brand" href="/">MoWEB</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="vr"></div>
            <div class="collapse navbar-collapse ms-1" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/Movies/List">Movies</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Management
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="/Movies/Create">Create Movie</a></li>
                        </ul>
                    </li>
                </ul>
                @await Component.InvokeAsync("Genres")
                <form class="d-flex" role="search" method="get" action="/Movies/List">
                    <input class="form-control me-2" type="search" name="q" placeholder="Search for movie" aria-label="Search">
                    <button class="btn btn-outline-secondary" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div class="container" style="margin-top: 100px;">
        @RenderBody()
    </div>

    <div class="container-fluid mt-auto">
        <footer class="my-4">
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <li class="nav-item"><a href="/Movies/List" class="nav-link px-2 text-body-secondary">Movies</a></li>
            </ul>
            <p class="text-center text-body-secondary">© 2023 WebTEAM - DOGUS</p>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

moWEBApp.web/Views/Shared/_category.cshtml
@model MoviesViewModel

<div class="dropdown me-2">
    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Categories
    </button>
    <ul class="dropdown-menu">
        @* @foreach(var genre in Model.Genres)
        {
            <li><a class="dropdown-item" href="#">@genre.Name</a></li>
        } *@
    </ul>
</div>